//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Restier.Publishers.OData.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Restier.Publishers.OData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument with name {0} cannot be null. ähnelt.
        /// </summary>
        internal static string ArguementsCannotbeNull {
            get {
                return ResourceManager.GetString("ArguementsCannotbeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} cannot write an object of type &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string CannotWriteObjectType {
            get {
                return ResourceManager.GetString("CannotWriteObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller cannot have null path. ähnelt.
        /// </summary>
        internal static string ControllerRequiresPath {
            get {
                return ResourceManager.GetString("ControllerRequiresPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently only EntitySets can be deleted from. ähnelt.
        /// </summary>
        internal static string DeleteOnlySupportedOnEntitySet {
            get {
                return ResourceManager.GetString("DeleteOnlySupportedOnEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is not a supported EDM type. ähnelt.
        /// </summary>
        internal static string EdmTypeNotSupported {
            get {
                return ResourceManager.GetString("EdmTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element type cannot be found for &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string ElementTypeNotFound {
            get {
                return ResourceManager.GetString("ElementTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EntitySet is missing during serialization. ähnelt.
        /// </summary>
        internal static string EntitySetMissingForSerialization {
            get {
                return ResourceManager.GetString("EntitySetMissingForSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keys were not specified in the format of &apos;KeyName=KeyValue&apos;. ähnelt.
        /// </summary>
        internal static string IncorrectKeyFormat {
            get {
                return ResourceManager.GetString("IncorrectKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently only EntitySets can be inserted into. ähnelt.
        /// </summary>
        internal static string InsertOnlySupportedOnEntitySet {
            get {
                return ResourceManager.GetString("InsertOnlySupportedOnEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid request - ODataPath is null. ähnelt.
        /// </summary>
        internal static string InvalidEmptyPathInRequest {
            get {
                return ResourceManager.GetString("InvalidEmptyPathInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid request - No ODataProperties. ähnelt.
        /// </summary>
        internal static string InvalidODataInfoInRequest {
            get {
                return ResourceManager.GetString("InvalidODataInfoInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid request - Expecting {0} path template. ähnelt.
        /// </summary>
        internal static string InvalidPathTemplateInRequest {
            get {
                return ResourceManager.GetString("InvalidPathTemplateInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specified key &apos;{0}&apos; is not a valid property of entity &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string KeyNotValidForEntityType {
            get {
                return ResourceManager.GetString("KeyNotValidForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model state is not valid with message {0}, please check your request. ähnelt.
        /// </summary>
        internal static string ModelStateIsNotValid {
            get {
                return ResourceManager.GetString("ModelStateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only one key was specified, when multiple were expected. ähnelt.
        /// </summary>
        internal static string MultiKeyValuesExpected {
            get {
                return ResourceManager.GetString("MultiKeyValuesExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not supported type: {0}. ähnelt.
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested operation is not implemented in Api class. ähnelt.
        /// </summary>
        internal static string OperationNotImplemented {
            get {
                return ResourceManager.GetString("OperationNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user is not authorized to execute operation {0}. ähnelt.
        /// </summary>
        internal static string OperationUnAuthorizationExecution {
            get {
                return ResourceManager.GetString("OperationUnAuthorizationExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path segment not supported: {0} ähnelt.
        /// </summary>
        internal static string PathSegmentNotSupported {
            get {
                return ResourceManager.GetString("PathSegmentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Post to unbound action is not supported by `RestierController`. ähnelt.
        /// </summary>
        internal static string PostToUnboundActionNotSupported {
            get {
                return ResourceManager.GetString("PostToUnboundActionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The request need to have If-Match or If-None-Match header. ähnelt.
        /// </summary>
        internal static string PreconditionRequired {
            get {
                return ResourceManager.GetString("PreconditionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resource you requested is not found. ähnelt.
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently only EntitySets can be updated. ähnelt.
        /// </summary>
        internal static string UpdateOnlySupportedOnEntitySet {
            get {
                return ResourceManager.GetString("UpdateOnlySupportedOnEntitySet", resourceCulture);
            }
        }
    }
}
