//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Restier.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Restier.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument with name {0} can not be null. ähnelt.
        /// </summary>
        internal static string ArgumentCanNotBeNull {
            get {
                return ResourceManager.GetString("ArgumentCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calling the methods in &apos;QueryableSource&apos; or &apos;QueryableSource&lt;T&gt;&apos; is not supported. ähnelt.
        /// </summary>
        internal static string CallQueryableSourceMethodNotSupported {
            get {
                return ResourceManager.GetString("CallQueryableSourceMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The change set cannot be set if there is already a result. ähnelt.
        /// </summary>
        internal static string CannotSetChangeSetIfThereIsResult {
            get {
                return ResourceManager.GetString("CannotSetChangeSetIfThereIsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The results source cannot be set if there is any error. ähnelt.
        /// </summary>
        internal static string CannotSetResultsSourceIfThereIsAnyError {
            get {
                return ResourceManager.GetString("CannotSetResultsSourceIfThereIsAnyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The total count cannot be set if there is no result yet. ähnelt.
        /// </summary>
        internal static string CannotSetTotalCountIfThereIsNoResult {
            get {
                return ResourceManager.GetString("CannotSetTotalCountIfThereIsNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change set preparer is missing. ähnelt.
        /// </summary>
        internal static string ChangeSetPreparerMissing {
            get {
                return ResourceManager.GetString("ChangeSetPreparerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A DataModification must be either: IsNew, IsUpdate, or IsDelete. ähnelt.
        /// </summary>
        internal static string DataModificationMustBeCUD {
            get {
                return ResourceManager.GetString("DataModificationMustBeCUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;DataModificationItem.ApplyTo cannot be called on an new resource. ähnelt.
        /// </summary>
        internal static string DataModificationNotSupportCreateResource {
            get {
                return ResourceManager.GetString("DataModificationNotSupportCreateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There should have been at least one predicate applied to the query from the resource key.  Ensure there is at least one resource key. ähnelt.
        /// </summary>
        internal static string DataModificationRequiresResourceKey {
            get {
                return ResourceManager.GetString("DataModificationRequiresResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do not call the methods in &apos;DataSourceStub&apos; directly. ähnelt.
        /// </summary>
        internal static string DoNotCallDataSourceStubMethodDirectly {
            get {
                return ResourceManager.GetString("DoNotCallDataSourceStubMethodDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is not a supported EDM type. ähnelt.
        /// </summary>
        internal static string EdmTypeNotSupported {
            get {
                return ResourceManager.GetString("EdmTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element type cannot be found for &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string ElementTypeNotFound {
            get {
                return ResourceManager.GetString("ElementTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element type not match. ähnelt.
        /// </summary>
        internal static string ElementTypeNotMatch {
            get {
                return ResourceManager.GetString("ElementTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expander cannot change the expression type. ähnelt.
        /// </summary>
        internal static string ExpanderCannotChangeExpressionType {
            get {
                return ResourceManager.GetString("ExpanderCannotChangeExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression must be queryable. ähnelt.
        /// </summary>
        internal static string ExpressionMustBeQueryable {
            get {
                return ResourceManager.GetString("ExpressionMustBeQueryable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inspection failed. ähnelt.
        /// </summary>
        internal static string InspectionFailed {
            get {
                return ResourceManager.GetString("InspectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid ChangeSetItem Type: {0}. ähnelt.
        /// </summary>
        internal static string InvalidChangeSetEntryType {
            get {
                return ResourceManager.GetString("InvalidChangeSetEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEdmModel cannot be generated since API service IModelBuilder is not registered. ähnelt.
        /// </summary>
        internal static string ModelBuilderNotRegistered {
            get {
                return ResourceManager.GetString("ModelBuilderNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current user does not have permission to delete entities from the EntitySet &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string NoPermissionToDeleteEntity {
            get {
                return ResourceManager.GetString("NoPermissionToDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current user does not have permission to insert entities into the EntitySet &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string NoPermissionToInsertEntity {
            get {
                return ResourceManager.GetString("NoPermissionToInsertEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current user does not have permission to invoke the requested action &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string NoPermissionToInvokeAction {
            get {
                return ResourceManager.GetString("NoPermissionToInvokeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current user does not have permission to update entities in the EntitySet &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string NoPermissionToUpdateEntity {
            get {
                return ResourceManager.GetString("NoPermissionToUpdateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not supported type: {0}. ähnelt.
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original query expression should be constant expression. ähnelt.
        /// </summary>
        internal static string OriginalExpressionShouldBeConstant {
            get {
                return ResourceManager.GetString("OriginalExpressionShouldBeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original query expression should contain a value which is queryable. ähnelt.
        /// </summary>
        internal static string OriginalExpressionShouldBeQueryable {
            get {
                return ResourceManager.GetString("OriginalExpressionShouldBeQueryable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The precondition check for request {0} on resource {1} is failed. ähnelt.
        /// </summary>
        internal static string PreconditionCheckFailed {
            get {
                return ResourceManager.GetString("PreconditionCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processor cannot change the expression type. ähnelt.
        /// </summary>
        internal static string ProcessorCannotChangeExpressionType {
            get {
                return ResourceManager.GetString("ProcessorCannotChangeExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;QueryableSource&apos; cannot be used as query. ähnelt.
        /// </summary>
        internal static string QueryableSourceCannotBeUsedAsQuery {
            get {
                return ResourceManager.GetString("QueryableSourceCannotBeUsedAsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query executor is missing. ähnelt.
        /// </summary>
        internal static string QueryExecutorMissing {
            get {
                return ResourceManager.GetString("QueryExecutorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query expression sourcer is missing. ähnelt.
        /// </summary>
        internal static string QuerySourcerMissing {
            get {
                return ResourceManager.GetString("QuerySourcerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The request resource is not found. ähnelt.
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should specify an interface type T for the handler. ähnelt.
        /// </summary>
        internal static string ShouldBeInterfaceType {
            get {
                return ResourceManager.GetString("ShouldBeInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression returned by sourcer is missing. ähnelt.
        /// </summary>
        internal static string SourceExpressionMissing {
            get {
                return ResourceManager.GetString("SourceExpressionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit executor is missing. ähnelt.
        /// </summary>
        internal static string SubmitExecutorMissing {
            get {
                return ResourceManager.GetString("SubmitExecutorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operation cannot be performed because one or more objects are invalid.  Please inspect the ChangeSetValidationException.ValidationResults property for more information. ähnelt.
        /// </summary>
        internal static string ValidationFailsTheOperation {
            get {
                return ResourceManager.GetString("ValidationFailsTheOperation", resourceCulture);
            }
        }
    }
}
